apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: quay-registry
  annotations:
    policy.open-cluster-management.io/standards: DevOps
    policy.open-cluster-management.io/categories: Image Registry
    policy.open-cluster-management.io/controls: Enterprise Registry
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: quay-namespace
      spec:
        remediationAction: inform
        severity: high
        object-templates:
          - complianceType: musthave
            objectDefinition:
                apiVersion: v1                    
                kind: Namespace
                metadata:
                  labels:
                    openshift.io/cluster-monitoring: "true"
                  name: quay
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: quay-operator
      spec:
        remediationAction: inform
        severity: high
        object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: operators.coreos.com/v1alpha1
              kind: Subscription
              metadata:
                name: quay-operator
                namespace: openshift-operators
              spec:
                channel: stable-3.7
                installPlanApproval: Automatic
                name: quay-operator
                source: redhat-operators
                sourceNamespace: openshift-marketplace
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: quay-deployment
      spec:
        remediationAction: inform
        severity: high
        object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: v1
              kind: Secret
              metadata:
                name: init-config-bundle-secret
                namespace: quay
              data:
                config.yaml: U1VQRVJfVVNFUlM6Ci0gcXVheWFkbWluCkZFQVRVUkVfVVNFUl9DUkVBVElPTjogdHJ1ZQpGRUFUVVJFX1BST1hZX0NBQ0hFOiB0cnVlCg==
          - complianceType: musthave
            objectDefinition:
              apiVersion: quay.redhat.com/v1
              kind: QuayRegistry
              metadata:
                name: registry
                namespace: quay
              spec:
                components:
                  - kind: objectstorage
                    managed: true
                  - managed: true
                    kind: tls
                configBundleSecret: init-config-bundle-secret
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-quay-registry
placementRef:
  name: placement-quay-registry
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: quay-registry
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-quay-registry
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: quay
        operator: In
        values:
          - "true"