apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitops-argocd-extended-clusterrole
rules:
  - apiGroups:
    - kafka.strimzi.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
    - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - '*'