apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: object-storage
  annotations:
    policy.open-cluster-management.io/standards: Storage
    policy.open-cluster-management.io/categories: Object
    policy.open-cluster-management.io/controls: S3 Compatible
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: object-storage-namespace
      spec:
        remediationAction: inform
        severity: high
        object-templates:
          - complianceType: musthave
            objectDefinition:
                apiVersion: v1                    
                kind: Namespace
                metadata:
                  labels:
                    openshift.io/cluster-monitoring: "true"
                  name: openshift-storage
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: ocs-operator
      spec:
        remediationAction: inform
        severity: high
        object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: operators.coreos.com/v1alpha1
              kind: Subscription
              metadata:
                name: ocs-operator
                namespace: openshift-storage
              spec:
                channel: stable-4.13
                installPlanApproval: Automatic
                name: odf-operator
                source: redhat-operators
                sourceNamespace: openshift-marketplace
          - complianceType: musthave
            objectDefinition:
              apiVersion: operators.coreos.com/v1
              kind: OperatorGroup
              metadata:
                name: openshift-storage
                namespace: openshift-storage
              spec:
                targetNamespaces:
                  - openshift-storage
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: object-storage-storagesystem
      spec:
        remediationAction: inform
        severity: high
        object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: odf.openshift.io/v1alpha1
              kind: StorageSystem
              metadata:
                name: ocs-storagecluster-storagesystem
                namespace: openshift-storage
              spec:
                kind: storagecluster.ocs.openshift.io/v1
                name: ocs-storagecluster
                namespace: openshift-storage
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: object-storage-storagecluster
      spec:
        remediationAction: inform
        severity: high
        object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: ocs.openshift.io/v1
              kind: StorageCluster
              metadata:
                name: ocs-storagecluster
                namespace: openshift-storage
              spec:
                arbiter: {}
                encryption:
                  kms: {}
                externalStorage: {}
                managedResources:
                  cephBlockPools: {}
                  cephCluster: {}
                  cephConfig: {}
                  cephDashboard: {}
                  cephFilesystems: {}
                  cephObjectStoreUsers: {}
                  cephObjectStores: {}
                mirroring: {}
                multiCloudGateway:
                  dbStorageClassName: gp3
                  reconcileStrategy: standalone
                version: 4.13.0
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-object-storage
placementRef:
  name: placement-object-storage
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: object-storage
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-object-storage
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: odfVersion
        operator: In
        values:
          - "4.13"
