apiVersion: v1                    
kind: Namespace
metadata:
  name: developer-gitops                             
---
apiVersion: v1                    
kind: Namespace
metadata:
  name: channel-developer-gitops                             
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: developer-gitops
  namespace: developer-gitops
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - developer-gitops
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
  name: developer-gitops
  namespace: channel-developer-gitops
spec:
  type: Git
  pathname: 'https://github.com/pittar-demos/acm-demo'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: gitops/openshift-gitops
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: developer-gitops
  name: developer-gitops-subscription
  namespace: developer-gitops
spec:
  channel: channel-developer-gitops/developer-gitops
  placement:
    placementRef:
      kind: PlacementRule
      name: developer-gitops-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: developer-gitops
  name: developer-gitops-placement
  namespace: developer-gitops
spec:
  clusterSelector:
    matchLabels:
      'developer-gitops': 'true'
