apiVersion: v1                    
kind: Namespace
metadata:
  name: application-acm-init                             
---
apiVersion: v1                    
kind: Namespace
metadata:
  name: channel-acm-init                             
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: acm-init
  namespace: application-acm-init
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - acm-init
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
  name: acm-init
  namespace: channel-acm-init
spec:
  type: Git
  pathname: 'https://github.com/pittar-demos/acm-demo'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: gitops/acm-init
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: acm-init
  name: acm-init-subscription
  namespace: application-acm-init
spec:
  channel: channel-acm-init/acm-init
  placement:
    placementRef:
      kind: PlacementRule
      name: acm-init-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: acm-init
  name: acm-init-placement
  namespace: application-acm-init
spec:
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'
