apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-crw-operator
  namespace: policy-crw-operator
  annotations:
    policy.open-cluster-management.io/standards: DevOps
    policy.open-cluster-management.io/categories: Developer IDE
    policy.open-cluster-management.io/controls: CodeReady Workspaces
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-crw-operator
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1                    
                kind: Namespace
                metadata:
                  name: openshift-workspaces     
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: codeready-workspaces
                  namespace: openshift-workspaces
                spec:
                  channel: latest
                  installPlanApproval: Automatic
                  name: codeready-workspaces
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: openshift-workspaces
                  namespace: openshift-workspaces
                spec:
                  targetNamespaces:
                    - openshift-workspaces
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-crw-operator
  namespace: policy-crw-operator
placementRef:
  name: placement-policy-crw-operator
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-crw-operator
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-crw-operator
  namespace: policy-crw-operator
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: devops-tools
        operator: In
        values:
          - "true"
