apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: pipelines-operator
  annotations:
    policy.open-cluster-management.io/standards: DevOps
    policy.open-cluster-management.io/categories: CI/CD Tools
    policy.open-cluster-management.io/controls: OpenShift Pipelines
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: pipelines-operator
        spec:
          remediationAction: inform
          severity: high
          object-templates:   
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: openshift-pipelines-operator
                  namespace: openshift-operators
                spec:
                  channel: stable
                  installPlanApproval: Automatic
                  name: openshift-pipelines-operator-rh
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-pipelines-operator
placementRef:
  name: placement-pipelines-operator
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: pipelines-operator
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-pipelines-operator
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: demo
        operator: In
        values:
          - "devops"
          - "security"
          - "all"
